var forms = [ 
    'present active infinitive',
    'present middle-passive infinitive',
    'future active infinitive',
    'future middle infinitive',
    'aorist active infinitive',
    'aorist middle infinitive',
    '1st person singular present indicative active',
    '1st person singular present indicative middle-passive',
    '1st person singular present subjunctive active',
    '1st person singular present subjunctive middle-passive',
    '1st person singular present optative active',
    '1st person singular present optative middle-passive',
    '1st person singular imperfect indicative active',
    '1st person singular imperfect indicative middle-passive',
    '1st person singular future indicative active',
    '1st person singular future indicative middle',
    '1st person singular future optative active',
    '1st person singular future optative middle',
    '1st person singular aorist indicative active',
    '1st person singular aorist indicative middle',
    '1st person singular aorist subjunctive active',
    '1st person singular aorist subjunctive middle',
    '1st person singular aorist optative active',
    '1st person singular aorist optative middle',
    '1st person plural present indicative active',
    '1st person plural present indicative middle-passive',
    '1st person plural present subjunctive active',
    '1st person plural present subjunctive middle-passive',
    '1st person plural present optative active',
    '1st person plural present optative middle-passive',
    '1st person plural imperfect indicative active',
    '1st person plural imperfect indicative middle-passive',
    '1st person plural future indicative active',
    '1st person plural future indicative middle',
    '1st person plural future optative active',
    '1st person plural future optative middle',
    '1st person plural aorist indicative active',
    '1st person plural aorist indicative middle',
    '1st person plural aorist subjunctive active',
    '1st person plural aorist subjunctive middle',
    '1st person plural aorist optative active',
    '1st person plural aorist optative middle',
    '2nd person singular present indicative active',
    '2nd person singular present indicative middle-passive',
    '2nd person singular present subjunctive active',
    '2nd person singular present subjunctive middle-passive',
    '2nd person singular present optative active',
    '2nd person singular present optative middle-passive',
    '2nd person singular imperfect indicative active',
    '2nd person singular imperfect indicative middle-passive',
    '2nd person singular future indicative active',
    '2nd person singular future indicative middle',
    '2nd person singular future optative active',
    '2nd person singular future optative middle',
    '2nd person singular aorist indicative active',
    '2nd person singular aorist indicative middle',
    '2nd person singular aorist subjunctive active',
    '2nd person singular aorist subjunctive middle',
    '2nd person singular aorist optative active',
    '2nd person singular aorist optative middle',
    '2nd person plural present indicative active',
    '2nd person plural present indicative middle-passive',
    '2nd person plural present subjunctive active',
    '2nd person plural present subjunctive middle-passive',
    '2nd person plural present optative active',
    '2nd person plural present optative middle-passive',
    '2nd person plural imperfect indicative active',
    '2nd person plural imperfect indicative middle-passive',
    '2nd person plural future indicative active',
    '2nd person plural future indicative middle',
    '2nd person plural future optative active',
    '2nd person plural future optative middle',
    '2nd person plural aorist indicative active',
    '2nd person plural aorist indicative middle',
    '2nd person plural aorist subjunctive active',
    '2nd person plural aorist subjunctive middle',
    '2nd person plural aorist optative active',
    '2nd person plural aorist optative middle',
    '3rd person singular present indicative active',
    '3rd person singular present indicative middle-passive',
    '3rd person singular present subjunctive active',
    '3rd person singular present subjunctive middle-passive',
    '3rd person singular present optative active',
    '3rd person singular present optative middle-passive',
    '3rd person singular imperfect indicative active',
    '3rd person singular imperfect indicative middle-passive',
    '3rd person singular future indicative active',
    '3rd person singular future indicative middle',
    '3rd person singular future optative active',
    '3rd person singular future optative middle',
    '3rd person singular aorist indicative active',
    '3rd person singular aorist indicative middle',
    '3rd person singular aorist subjunctive active',
    '3rd person singular aorist subjunctive middle',
    '3rd person singular aorist optative active',
    '3rd person singular aorist optative middle',
    '3rd person plural present indicative active',
    '3rd person plural present indicative middle-passive',
    '3rd person plural present subjunctive active',
    '3rd person plural present subjunctive middle-passive',
    '3rd person plural present optative active',
    '3rd person plural present optative middle-passive',
    '3rd person plural imperfect indicative active',
    '3rd person plural imperfect indicative middle-passive',
    '3rd person plural future indicative active',
    '3rd person plural future indicative middle',
    '3rd person plural future optative active',
    '3rd person plural future optative middle',
    '3rd person plural aorist indicative active',
    '3rd person plural aorist indicative middle',
    '3rd person plural aorist subjunctive active',
    '3rd person plural aorist subjunctive middle',
    '3rd person plural aorist optative active',
    '3rd person plural aorist optative middle'
]

function newForm() {
	var randomNumber = Math.floor(Math.random() * (forms.length));
	document.getElementById('formDisplay').innerHTML = forms[randomNumber];
}